server:
  port: 16115

spring:
  application:
    name: ts-admin-user-service

swagger:
  controllerPackage: adminuser.controller

adminuser:
  config:
    url: http://ts-user-service:12342/api/v1/userservice/users