server:
  port: 16112

spring:
  application:
    name: ts-admin-order-service
  data:
    mongodb:
      host: ts-travel-mongo
      database: ts
      port: 27017


swagger:
  controllerPackage: adminorder.controller