server:
  port: 12347

spring:
  application:
    name: ts-contacts-service
  data:
    mongodb:
      host: ts-contacts-mongo
      database: ts
      port: 27017

swagger:
  controllerPackage: contacts.controller

contacts:
  config:
    url: http://ts-station-service:12345/api/v1/stationservice